name: deploy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm manual build & deploy on master'
        required: true
        default: 'no'

env:
  APP_NAME: kartel
  MAIN_PATH: /home/mfirhas/kartel
  HTTP_PORT: 3000
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'yes'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ inputs.tag }},enable=${{ inputs.tag != '' }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            PORT=${{ env.HTTP_PORT }}
   
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.event.inputs.confirm == 'yes'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Creating and Login to Ephemeral Node
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:pfm-prod-cd

      - name: Check Connectivity
        run: |
          tailscale ping ubuntu

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          cat >> ~/.ssh/config << 'EOF'
          Host *
            StrictHostKeyChecking no
            UserKnownHostsFile=/dev/null
            LogLevel ERROR
          EOF
          chmod 600 ~/.ssh/config

      - name: Login
        run: |
          scp docker-compose.yml -tt pfm@ubuntu:/home/pfm/

      # - name: Copy docker-compose.yml
      #   uses: appleboy/scp-action@v1
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USERNAME }}
      #     key: ${{ secrets.VPS_SSH_KEY }}
      #     port: ${{ secrets.VPS_PORT }}
      #     source: "docker-compose.yml"
      #     target: "~/${{ env.APP_NAME }}"
      
      # - name: Deployment
      #   uses: appleboy/ssh-action@v1.0.3
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USERNAME }}
      #     key: ${{ secrets.VPS_SSH_KEY }}
      #     port: ${{ secrets.VPS_PORT }}
      #     script: |
      #       sudo cp ~/${{ env.APP_NAME }}/docker-compose.yml ${{ env.MAIN_PATH }}/docker-compose.yml
      #       sudo chown mfirhas:mfirhas ${{ env.MAIN_PATH }}/docker-compose.yml
      #       sudo chmod 640 ${{ env.MAIN_PATH }}/docker-compose.yml

      #       MAIN_PATH="${{ env.MAIN_PATH }}"
      #       GHCR_PAT="${{ secrets.GHCR_PAT }}"
      #       GHCR_USERNAME="${{ secrets.GHCR_USERNAME }}"

      #       echo "$GHCR_PAT" | sudo -u mfirhas /usr/bin/docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin

      #       echo "pulling docker image..."
      #       sudo -u mfirhas /usr/bin/docker compose -f $MAIN_PATH/docker-compose.yml pull

      #       echo "tearing down current running container..."
      #       sudo -u mfirhas /usr/bin/docker compose -f $MAIN_PATH/docker-compose.yml down

      #       echo "starting up from new image..."
      #       sudo -u mfirhas /usr/bin/docker compose -f $MAIN_PATH/docker-compose.yml up -d --remove-orphans
      #       sleep 5

      #       echo "docker status"
      #       sudo -u mfirhas /usr/bin/docker compose -f $MAIN_PATH/docker-compose.yml ps

      #       echo "docker logs"
      #       sudo -u mfirhas /usr/bin/docker compose -f $MAIN_PATH/docker-compose.yml logs --tail=10 kartel

      #       echo "clean up old images"
      #       sudo -u mfirhas /usr/bin/docker image prune -f

      #       echo "ðŸŽ‰ðŸŽ‰ðŸŽ‰ DEPLOYMENT COMPLETE ðŸŽ‰ðŸŽ‰ðŸŽ‰"
