name: deploy

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm manual deploy on master'
        required: true
        default: 'no'

jobs:
  build:
    name: Build
    # TODO

  deploy:
    name: Deploy
    # TODO
